(function(g){var window=this;var x5=function(a,b,c){var d=b.bc();g.U(a.element,"ytp-suggestion-set",!!d.videoId);var e=b.getPlaylistId();c=b.jd(c?c:"mqdefault.jpg");var f=b instanceof g.DO&&b.lengthSeconds?g.aV(b.lengthSeconds):null,k=!!e;e=k&&"RD"==(new g.vQ(e.substr(0,2),e.substr(2))).type;var l=b instanceof g.DO?b.La:null;d={title:b.title,author:b.author,author_and_views:d.shortViewCount?b.author+" \u2022 "+d.shortViewCount:b.author,aria_label:b.Rl||g.dH("YTP_WATCH_VIDEO_OR_PLAYLIST",{TITLE:b.title},b.title),duration:f,url:b.Fm(),
is_live:l,is_list:k,is_mix:e,background:c?"background-image: url("+c+")":""};b instanceof g.xQ&&(d.playlist_length=b.getLength());a.update(d)},y5=function(a,b){g.DH.call(this,{I:"div",
fa:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.player=a;this.created=!1},z5=function(a){g.W.call(this,{I:"div",
M:"ytp-upnext",U:{"aria-label":"{{aria_label}}"},P:[{I:"div",M:"ytp-cued-thumbnail-overlay-image",U:{style:"{{background}}"}},{I:"span",M:"ytp-upnext-top",P:[{I:"span",M:"ytp-upnext-header",da:"Up Next"},{I:"span",M:"ytp-upnext-title",da:"{{title}}"},{I:"span",M:"ytp-upnext-author",da:"{{author}}"}]},{I:"a",M:"ytp-upnext-autoplay-icon",U:{role:"button",href:"{{url}}","aria-label":"Play next video"},P:[{I:"svg",U:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},P:[{I:"circle",M:"ytp-svg-autoplay-circle",
U:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{I:"circle",M:"ytp-svg-autoplay-ring",U:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{I:"path",M:"ytp-svg-fill",U:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{I:"span",M:"ytp-upnext-bottom",P:[{I:"span",M:"ytp-upnext-cancel"},{I:"span",M:"ytp-upnext-paused",da:"Autoplay is paused"}]}]});this.F=null;
var b=this.o["ytp-upnext-cancel"];this.F=new g.W({I:"button",fa:["ytp-upnext-cancel-button","ytp-button"],U:{tabindex:"0","aria-label":"Cancel autoplay"},da:"Cancel"});g.N(this,this.F);this.F.W("click",this.sS,this);this.F.xa(b);this.B=a;this.L=this.o["ytp-svg-autoplay-ring"];this.H=this.G=this.C=this.D=null;this.J=new g.V(this.No,5E3,this);g.N(this,this.J);this.K=0;this.R(this.o["ytp-upnext-autoplay-icon"],"click",this.EU);this.VD();this.R(a,"autonavvisibility",this.VD);this.R(a,"mdxnowautoplaying",
this.TT);this.R(a,"mdxautoplaycanceled",this.UT);this.R(a,"mdxautoplayupnext",this.EG);3==this.B.Sa()&&(a=(a=g.ZT(g.RT(this.B)))?a.tL():null)&&this.EG(a)},A5=function(a,b){if(!a.C){g.cG("a11y-announce","Up Next "+a.D.title);
a.K=g.nG();a.C=new g.V((0,g.B)(a.us,a,b),25);a.us(b);var c=b||g.Y(a.B).experiments.A("autoplay_time")||1E4;a.B.ya("onAutonavCoundownStarted",c)}g.Eq(a.element,"ytp-upnext-autoplay-paused")},C5=function(a){B5(a);
a.K=g.nG();a.us();g.T(a.element,"ytp-upnext-autoplay-paused")},B5=function(a){a.C&&(a.C.dispose(),a.C=null)},D5=function(a,b){b=void 0===b?!1:b;
if(g.Y(a.B).experiments.o("autonav_notifications")&&b&&window.Notification&&window.document.hasFocus){var c=window.Notification.permission;"default"==c?window.Notification.requestPermission():"granted"!=c||window.document.hasFocus()||(c=a.D.bc(),a.No(),a.G=new window.Notification("Up Next",{body:c.title,icon:c.jd()}),a.H=a.R(a.G,"click",a.uU),a.J.start())}B5(a);a.B.Yk(!1,b)},vCa=function(a){y5.call(this,a,"subscribecard-endscreen");
var b=a.getVideoData();this.B=new g.W({I:"div",M:"ytp-subscribe-card",P:[{I:"img",M:"ytp-author-image",U:{src:b.profilePicture}},{I:"div",M:"ytp-subscribe-card-right",P:[{I:"div",M:"ytp-author-name",da:b.author},{I:"div",M:"html5-subscribe-button-container"}]}]});g.N(this,this.B);this.B.xa(this.element);this.C=new g.HZ("Subscribe",null,"Unsubscribe",null,!0,!1,b.Fl,b.subscribed,"trailer-endscreen",null,null,a);g.N(this,this.C);this.C.xa(this.B.o["html5-subscribe-button-container"]);this.hide()},E5=
function(a){var b=g.Y(a),c=g.pI||g.qf?{style:"will-change: opacity"}:void 0,d=b.o,e=["ytp-videowall-still"];
b.B&&e.push("ytp-videowall-show-text");g.W.call(this,{I:"a",fa:e,U:{href:"{{url}}",target:d?"_blank":"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},P:[{I:"div",M:"ytp-videowall-still-image",U:{style:"{{background}}"}},{I:"span",M:"ytp-videowall-still-info",P:[{I:"span",M:"ytp-videowall-still-info-bg",P:[{I:"span",M:"ytp-videowall-still-info-content",U:c,P:[{I:"span",M:"ytp-videowall-still-info-title",da:"{{title}}"},{I:"span",
M:"ytp-videowall-still-info-author",da:"{{author_and_views}}"},{I:"span",M:"ytp-videowall-still-info-live",da:"Live"},{I:"span",M:"ytp-videowall-still-info-duration",da:"{{duration}}"}]}]}]},{I:"span",fa:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],P:[{I:"span",M:"ytp-videowall-still-listlabel-icon"},"Playlist",{I:"span",M:"ytp-videowall-still-listlabel-length",P:[" (",{I:"span",da:"{{playlist_length}}"},")"]}]},{I:"span",fa:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],
P:[{I:"span",M:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{I:"span",M:"ytp-videowall-still-listlabel-length",da:" (50+)"}]}]});this.F=d;this.B=a;this.C=null;this.D=new g.MF(this);g.N(this,this.D);this.W("click",this.H);this.W("keypress",this.J);this.D.R(a,"videodatachange",this.G);g.Y(a).Y&&(a=a.app.la,b=this.element,g.Na(a.o,b),g.Qa(a.o,b),c=String(a.H++),b.setAttribute("data-visual-id",c),g.kf(this,(0,g.B)(a.G,a,b)));this.G()},F5=function(a){y5.call(this,a,"videowall-endscreen");
this.K=a;this.G=0;this.C=[];this.H=this.F=this.D=null;this.J=this.O=!1;this.Z=new g.MF(this);g.N(this,this.Z);this.L=new g.V(g.Da(g.T,this.element,"ytp-show-tiles"),0);g.N(this,this.L);var b=new g.W({I:"button",fa:["ytp-button","ytp-endscreen-previous"],U:{"aria-label":"Previous"},P:[g.UU()]});g.N(this,b);b.xa(this.element);b.W("click",this.sQ,this);this.N=new g.xH({I:"div",M:"ytp-endscreen-content"});g.N(this,this.N);this.N.xa(this.element);b=new g.W({I:"button",fa:["ytp-button","ytp-endscreen-next"],
U:{"aria-label":"Next"},P:[g.VU()]});g.N(this,b);b.xa(this.element);b.W("click",this.rQ,this);this.B=new z5(a);g.N(this,this.B);g.rU(this.player,this.B.element,4);this.hide()},G5=function(a){return g.tU(a.player)&&a.hz()&&!a.H},wCa=function(a,b){return(0,g.I)(b.suggestions,function(b){b=g.DX(g.Y(a.K),b);
g.N(a,b);return b})},H5=function(a){var b=a.zv();
b!=a.O&&(a.O=b,a.player.V("autonavvisibility"))},I5=function(a){g.BU.call(this,a);
this.o=null;this.A=new g.MF(this);g.N(this,this.A);this.B=g.Y(a);xCa(a)?this.o=new F5(this.player):this.B.Fa?this.o=new vCa(this.player):this.o=new y5(this.player);g.N(this,this.o);g.rU(this.player,this.o.element,4);this.qF();this.A.R(a,"videodatachange",this.qF,this);this.A.R(a,"crn_endscreen",this.sO,this);this.A.R(a,"crx_endscreen",this.tO,this)},xCa=function(a){a=g.Y(a);
return a.Vc&&!a.Fa};
g.r(y5,g.DH);y5.prototype.create=function(){this.created=!0};
y5.prototype.destroy=function(){this.created=!1};
y5.prototype.hz=function(){return!1};
y5.prototype.zv=function(){return!1};g.r(z5,g.W);g.h=z5.prototype;g.h.No=function(){this.G&&(this.J.stop(),this.Ha(this.H),this.H=null,this.G.close(),this.G=null)};
g.h.VD=function(){g.CH(this,g.ST(this.B))};
g.h.uU=function(){window.focus();this.No()};
g.h.hide=function(){g.W.prototype.hide.call(this)};
g.h.us=function(a){a=a||g.Y(this.B).experiments.A("autoplay_time")||1E4;var b=Math.min(g.nG()-this.K,a);a=Math.min(b/a,1);this.L.setAttribute("stroke-dashoffset",-211*(a+1));1<=a&&3!=this.B.Sa()?D5(this,!0):this.C&&this.C.start()};
g.h.EU=function(a){!g.$d(this.F.element,g.AF(a))&&g.EW(a,this.B)&&D5(this)};
g.h.sS=function(){g.VT(this.B,!0)};
g.h.TT=function(a){this.B.Sa();this.show();A5(this,a)};
g.h.EG=function(a){this.B.Sa();this.D&&this.D.bc().videoId==a.bc().videoId||(this.D=a,x5(this,a,"hqdefault.jpg"))};
g.h.UT=function(){this.B.Sa();B5(this);this.hide()};
g.h.X=function(){B5(this);this.No();g.W.prototype.X.call(this)};g.r(vCa,y5);g.r(E5,g.W);E5.prototype.vl=function(){g.wU(this.B,this.element);var a=this.C.bc().videoId,b=this.C.getPlaylistId();g.Z_(this.B.app,a,this.C.Hd,b,void 0,void 0,void 0)};
E5.prototype.H=function(a){g.EW(a,this.B,this.F,this.C.Hd||void 0)&&this.vl()};
E5.prototype.J=function(a){switch(a.keyCode){case 13:case 32:g.FF(a)||(this.vl(),g.EF(a))}};
E5.prototype.G=function(){var a=this.B.getVideoData(),b=g.Y(this.B);this.F=a.isDni?!1:b.o};g.r(F5,y5);g.h=F5.prototype;g.h.create=function(){y5.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.D=wCa(this,a),this.F=a);this.kh();this.Z.R(this.player,"appresize",this.kh);this.Z.R(this.player,"onVideoAreaChange",this.kh);this.Z.R(this.player,"videodatachange",this.tQ);this.Z.R(this.player,"autonavchange",this.QC);this.Z.R(this.player,"autonavcancel",this.qQ);this.Z.R(this.element,"transitionend",this.WV)};
g.h.destroy=function(){g.OF(this.Z);g.nf(this.C);this.C=[];this.D=null;y5.prototype.destroy.call(this);g.Eq(this.element,"ytp-show-tiles");this.L.stop()};
g.h.hz=function(){return 1!=this.F.autonavState};
g.h.show=function(){y5.prototype.show.call(this);g.Eq(this.element,"ytp-show-tiles");g.Y(this.player).B?g.ru(this.L):this.L.start();(this.J||this.H&&this.H!=this.F.clientPlaybackNonce)&&g.VT(this.player,!1);G5(this)?(H5(this),2==this.F.autonavState?g.Y(this.player).experiments.o("fast_autonav_in_background")&&3==this.player.wj()?D5(this.B,!0):A5(this.B):3==this.F.autonavState&&C5(this.B)):(g.VT(this.player,!0),H5(this))};
g.h.hide=function(){y5.prototype.hide.call(this);C5(this.B);H5(this)};
g.h.WV=function(a){g.AF(a)==this.element&&this.kh()};
g.h.kh=function(){if(this.D&&this.D.length){g.T(this.element,"ytp-endscreen-paginate");var a=g.iU(this.K,!0),b=g.RH(this.K);b&&(b=b.md()?48:32,a.width-=2*b);var c=a.width/a.height,d=96/54,e=b=2,f=Math.max(a.width/96,2),k=Math.max(a.height/54,2),l=this.D.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(b<f||e<k);){var p=b/2,t=e/2,w=b<=f-2&&n>=t*m,z=e<=k-2&&n>=p*m;if((p+1)/t*d/c>c/(p/(t+1)*d)&&z)n-=p*m,e+=2;else if(w)n-=t*m,b+=2;else if(z)n-=p*m,e+=2;else break}d=
!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=b)&&(d=!0);m=96*b;n=54*e;c=m/n<c?a.height/n:a.width/m;c=Math.min(c,2);m*=c;n*=c;m*=g.md(a.width/m||1,1,1.21);n*=g.md(a.height/n||1,1,1.21);m=Math.floor(Math.min(a.width,m));n=Math.floor(Math.min(a.height,n));a=this.N.element;g.Ph(a,m,n);g.xh(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});c=this.B;f=this.D[0];c.D=f;x5(c,f,"hqdefault.jpg");g.U(this.element,"ytp-endscreen-takeover",G5(this));H5(this);m+=4;n+=4;for(f=c=0;f<b;f++)for(k=0;k<e;k++)if(p=c,t=0,d&&f>=b-2&&k>=e-
2?t=1:0==k%2&&0==f%2&&(2>k&&2>f?0==k&&0==f&&(t=2):t=2),p=g.nd(p+this.G,l),0!=t){w=this.C[c];w||(w=new E5(this.player),this.C[c]=w,a.appendChild(w.element));z=Math.floor(n*k/e);var E=Math.floor(m*f/b),J=Math.floor(n*(k+t)/e)-z-4,Q=Math.floor(m*(f+t)/b)-E-4;g.Eh(w.element,E,z);g.Ph(w.element,Q,J);g.xh(w.element,"transitionDelay",(k+f)/20+"s");g.U(w.element,"ytp-videowall-still-mini",1==t);g.U(w.element,"ytp-videowall-still-large",2<t);t=w;p=this.D[p];t.C!=p&&(t.C=p,x5(t,p,g.Cq(t.element,"ytp-videowall-still-large")?
"hqdefault.jpg":"mqdefault.jpg"),w=(p=p.Hd)&&p.itct)&&(p=t.B,g.Y(p).Y&&(p=p.app.la,t=t.element,z=t.getAttribute("data-visual-id"),g.Na(p.o,t),g.uU(p,"onLogServerVeCreated",{id:z,tracking_params:w})));c++}g.U(this.element,"ytp-endscreen-paginate",c<l);for(b=this.C.length-1;b>=c;b--)e=this.C[b],g.Ud(e.element),g.lf(e);this.C.length=c}};
g.h.tQ=function(){var a=this.player.getVideoData();this.F!=a&&(this.G=0,this.D=wCa(this,a),this.F=a,this.kh())};
g.h.rQ=function(){this.G+=this.C.length;this.kh()};
g.h.sQ=function(){this.G-=this.C.length;this.kh()};
g.h.wN=function(){return!!this.B.C};
g.h.QC=function(a){1==a?(this.J=!1,this.H=this.F.clientPlaybackNonce,B5(this.B),this.A&&this.kh()):(this.J=!0,this.A&&G5(this)&&(2==a?A5(this.B):3==a&&C5(this.B)))};
g.h.qQ=function(a){if(a){for(a=0;a<this.C.length;a++)g.xU(this.K,this.C[a].element,!0);this.QC(1)}else this.H=null,this.J=!1;this.kh()};
g.h.zv=function(){return this.A&&G5(this)};g.r(I5,g.BU);g.h=I5.prototype;g.h.oC=function(){var a=this.player.getVideoData(),b=!!(a&&a.suggestions&&a.suggestions.length);b=!xCa(this.player)||b;a=g.eP(a,"ypc_module");var c=g.C_(this.player.app);return b&&!a&&!c};
g.h.nC=function(){return this.o.zv()};
g.h.sN=function(){return this.nC()?this.o.wN():!1};
g.h.X=function(){g.pU(this.player,"endscreen");g.BU.prototype.X.call(this)};
g.h.load=function(){g.BU.prototype.load.call(this);this.o.show()};
g.h.unload=function(){g.BU.prototype.unload.call(this);this.o.hide();this.o.destroy()};
g.h.sO=function(a){this.oC()&&(this.o.created||this.o.create(),"load"==a.getId()&&this.load())};
g.h.tO=function(a){"load"==a.getId()&&this.loaded&&this.unload()};
g.h.qF=function(){g.pU(this.player,"endscreen");var a=Math.max(1E3*(this.player.getVideoData().lengthSeconds-10),0);a=new g.tQ(a,0x8000000000000,{id:"preload",namespace:"endscreen"});g.N(this,a);var b=new g.tQ(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});g.N(this,b);g.lU(this.player,[a,b])};g.yX.endscreen=I5;})(_yt_player);
