(function(g){var window=this;var g6=function(a){g.DH.call(this,{I:"div",M:"ytp-miniplayer-ui"});this.player=a;this.K=!1;this.J=this.F=this.B=void 0;this.R(a,"minimized",this.iU);this.R(a,"onStateChange",this.AX)},h6=function(a){g.BU.call(this,a);
this.o=new g6(this.player);this.o.hide();g.rU(this.player,this.o.element,4);a.app.L.o&&(this.load(),g.U(a.getRootNode(),"ytp-player-minimized",!0))};
g.r(g6,g.DH);g.h=g6.prototype;
g.h.show=function(){this.B=new g.nu(this.yQ,null,this);this.B.start();if(!this.K){this.H=new g.KZ(this.player,this);g.N(this,this.H);g.rU(this.player,this.H.element,4);this.H.F=.6;this.O=new g.iZ(this.player);g.N(this,this.O);this.G=new g.W({I:"div",M:"ytp-miniplayer-scrim"});g.N(this,this.G);this.G.xa(this.element);this.R(this.G.element,"click",this.DE);var a=new g.W({I:"button",fa:["ytp-miniplayer-close-button","ytp-button"],U:{"aria-label":"Close"},P:[g.WU()]});g.N(this,a);a.xa(this.G.element);
this.R(a.element,"click",this.UC);this.D=new g.W({I:"div",M:"ytp-miniplayer-controls"});g.N(this,this.D);this.D.xa(this.G.element);this.R(this.D.element,"click",this.DE);var b=new g.W({I:"div",M:"ytp-miniplayer-button-container"});g.N(this,b);b.xa(this.D.element);a=new g.W({I:"div",M:"ytp-miniplayer-play-button-container"});g.N(this,a);a.xa(this.D.element);var c=new g.W({I:"div",M:"ytp-miniplayer-button-container"});g.N(this,c);c.xa(this.D.element);this.N=new g.iY(this.player,this,!1);g.N(this,this.N);
this.N.xa(b.element);b=new g.gY(this.player,this);g.N(this,b);b.xa(a.element);this.L=new g.iY(this.player,this,!0);g.N(this,this.L);this.L.xa(c.element);this.J=new g.WY(this.player,this);g.N(this,this.J);this.J.xa(this.G.element);this.F=new g.jY(this.player,this);g.N(this,this.F);g.rU(this.player,this.F.element,4);this.C=new g.W({I:"div",M:"ytp-miniplayer-buttons"});g.N(this,this.C);g.rU(this.player,this.C.element,4);this.C.hide();a=new g.W({I:"button",fa:["ytp-miniplayer-close-button","ytp-button"],
U:{"aria-label":"Close"},P:[g.WU()]});g.N(this,a);a.xa(this.C.element);this.R(a.element,"click",this.UC);a=new g.W({I:"button",fa:["ytp-miniplayer-replay-button","ytp-button"],U:{"aria-label":"Close"},P:[g.XU()]});g.N(this,a);a.xa(this.C.element);this.R(a.element,"click",this.jV);this.R(this.player,"presentingplayerstatechange",this.zQ);this.R(this.player,"appresize",this.Cv);this.R(this.player,"fullscreentoggled",this.Cv);this.Cv();this.K=!0}0!=this.player.mi()&&g.DH.prototype.show.call(this);this.F.show();
this.player.pn("annotations_module")};
g.h.hide=function(){this.B&&(this.B.dispose(),this.B=void 0);g.DH.prototype.hide.call(this);this.player.app.L.o||(this.K&&this.F.hide(),this.player.Xk("annotations_module"))};
g.h.X=function(){this.B&&(this.B.dispose(),this.B=void 0);g.DH.prototype.X.call(this)};
g.h.UC=function(){this.player.Wd();this.player.ya("onCloseMiniplayer")};
g.h.jV=function(){this.player.bd()};
g.h.DE=function(a){if(a.target==this.G.element||a.target==this.D.element)g.Y(this.player).experiments.o("kevlar_miniplayer_scrim_pause")?2==this.player.mi()?this.player.bd():this.player.nd():this.player.ya("onExpandMiniplayer")};
g.h.iU=function(){g.U(this.player.getRootNode(),"ytp-player-minimized",this.player.app.L.o);this.player.app.L.o&&0==this.player.mi()?this.C.show():this.C.hide()};
g.h.yQ=function(){g.Ita(this.F);this.J.C();this.B&&this.B.start()};
g.h.zQ=function(a){g.X(a.state,32)&&this.H.hide()};
g.h.Cv=function(){var a=this.F,b=g.XT(this.player).Ua().width;a.Ka=0;a.F=b;a.H=!1;g.lY(a)};
g.h.AX=function(a){this.player.app.L.o&&(0==a?(this.hide(),this.C.show()):(this.show(),this.C.hide()))};
g.h.Ub=function(){return this.H};
g.h.md=function(){return!1};
g.h.Kk=function(){return!1};
g.h.RF=function(){};
g.h.Wo=function(){};
g.h.Xo=function(){};
g.h.wn=function(){return null};
g.h.Av=function(){return new g.jh(0,0,0,0)};
g.h.Bv=function(){};
g.h.Gq=function(a,b,c){a.style.left="";a.style.top="";a.style.bottom="";var d=g.Qh(a),e=g.XT(this.player).Ua().width;b&&["ytp-prev-button","ytp-next-button"].some(function(a){return g.Cq(b,a)})?(c=12,a.style.top="12px"):(c-=d.width/2,a.style.bottom="25px");
a.style.left=g.md(c,0,e-d.width)+"px"};
g.h.oq=function(){};
g.h.Dv=function(){};g.r(h6,g.BU);h6.prototype.init=function(){};
h6.prototype.load=function(){this.player.HC();this.o.show()};
h6.prototype.unload=function(){this.player.JC();this.o.hide()};g.yX.miniplayer=h6;})(_yt_player);
